main: ex.cpp
	clang++ -I /usr/local/include -F /Library/Frameworks -framework sfml-audio -framework sfml-window -framework sfml-graphics -framework sfml-system ex.cpp -framework OpenGL -framework GLUT -o ex.cpp.out
