# Project: Queue
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Queue.o
LINKOBJ  = main.o Queue.o
LIBS     = -L"C:/App/Dev-Cpp/MinGW64/lib" -L"C:/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/App/Dev-Cpp/MinGW64/include" -I"C:/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/App/Dev-Cpp/MinGW64/include" -I"C:/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Queue.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Queue.o: Queue.cpp
	$(CPP) -c Queue.cpp -o Queue.o $(CXXFLAGS)
