#pragma once
#include <iostream>
#include <SFML\Audio.hpp>
#include <SFML\Graphics.hpp>
#include <string>
#include <memory>
#include <map>
#include <vector>
#include <thread>
#include <array>
#include <assert.h>
#include <algorithm>
#include <cassert>
#include <functional>
#include <cmath>
#include <stdexcept>
#include <queue>
#include <limits>
#include <random>
#include <ctime>
#include "ResourceHolder.h"
#include "ResourceIdentifiers.h"
#include "StateIdentifiers.h"
#include "Utility.h"
#include "Foreach.h"
#include <set>
#include <list>